# ========== SERVER ==========
# indica donde correr Spring Boot (puerto 8080) (accedo desde //localhost:8080/)
server.port=8080
# convención profesional para dejar claro que es una API
server.servlet.context-path=/api

# ========== DATABASE ==========
# Le dice a Spring Boot que se conecte a postgrSQL en el puerto 5432 de mi computadora (LocalHost) en la base de datos equifitapp
spring.datasource.url=jdbc:postgresql://localhost:5432/equifitapp
# Credenciales (IMPORTANTE) --> (¡¡¡¡¡¡después cambiar password por variable de entorno (${DB_PASSWORD})!!!!!!)
spring.datasource.username=equifit_user
spring.datasource.password=EquiFit2026
# Le dice a Spring Boot cual es el Driver para conectar a PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ========== JPA / HIBERNATE ==========
# JPA: estándar para manejar BD desde JAVA sin SQL
# HIBERNATE: implementación de JPA más popular, traduce código JAVA en comandos SQL
# Le dice a Hibernate que va a usar PostgreSQL y que use su dialecto
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Hace que cuando arranque Spring Boot Hibernate compare las clases con @Entity con las tablas de la base de datos y las actualice si hubo cambios (UPDATE: crea/modifica sin perder datos)
spring.jpa.hibernate.ddl-auto=update
# si es true muestra en la consola todo el SQL que hibernate ejecuta (poner en true para debuggear y ver el SQL)
spring.jpa.show-sql=false
# Formatea el SQL para que sea legible (siempre que show-sql sea true)
spring.jpa.properties.hibernate.format_sql=true

# ========== LOGGING ==========
# logging sirve para imprimir mensajes en consola
# al colocar en INFO muestra 3,4 y 5 (ignora 1 y 2)
# (1. `TRACE` - Detalles muy específicos (raro); 2. `DEBUG` - Info para debugging; 3. `INFO` - Info general; 4. `WARN` - Advertencia; 5. `ERROR` - Error)
# .root es para todas las librerías y mi código
logging.level.root=INFO
#.com.equifitapp es para mi código (muestra 2,3,4 y 5)
logging.level.com.equifitapp=DEBUG

# ========== DEVELOPMENT ==========
# Spring Boot reinicia automáticamente cuando cambio código
spring.devtools.restart.enabled=true

